# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Comment'),
        ),
    ]
